# Stay on the Scala 3 LTS line (3.3.x)
updates.pin = [
  { groupId = "org.scala-lang", artifactId = "scala3-library", version = "3.3." },
  { groupId = "org.scala-lang", artifactId = "scala3-compiler", version = "3.3." }
]
